spring.application.name=Enterprise-Patient-Management-System

server.port=7979

# MySQL Database Connection Settings

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/healthcare_db
spring.datasource.username=root
spring.datasource.password=root


# Hibernate and JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf Settings (Disables cache so HTML changes show up immediately)
spring.thymeleaf.cache=false